### ISSUE TITLE
Stability file requires full path but not mentionned in the README.md

### ISSUE THREAD

**Issue by glihm** [M-Mysara/OCToPUS#2]
Dear M. Mysara,

I am trying to use OCToPUS to run a 16S NGS data analysis. In the README.md, towards the **stability.files**, it is not mentionned that files have to contain full path.

Without it, the program says: 

> Please check if the forward file is properly added in: SampleID ...

It may be a good thing to add in the example. I have tried to move the stability.files in the same directory as the raw_data, but it still not working. Adding the path, everything seems to be ok.

**_Sample1 /YOUR/PATH/Sample1_L001_R1_001.fastq /YOUR/PATH/Sample1_L001_R2_001.fastq_**

Thanks !

**Comment by M-Mysara** [comment]
Dear Glihm,
Thanks a lot for your remark, I have adjusted the read me accordingly.

Mohamed
